import { createFileRoute, Link, notFound } from '@tanstack/react-router'
import { ArrowRight, BookOpen, Boxes, Check, Code2, FileJson, Globe2, Headphones, HeartHandshake, Landmark, Layers3, LifeBuoy, MessageSquareText, PlugZap, Scale, ShieldCheck, ShoppingBag, TerminalSquare, Workflow } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { MarketingLayout } from '@/components/site-shell'
import { pricingPlans } from '@/lib/product'

export const Route = createFileRoute('/$page')({
  beforeLoad: ({ params }) => {
    if (!['features', 'solutions', 'pricing', 'developers', 'documentation', 'contact'].includes(params.page)) throw notFound()
  },
  component: PublicPage,
})

const pageData = {
  features: { eyebrow: 'PRODUCT CAPABILITIES', title: 'A complete control plane for every conversation transfer.', text: 'Build, operate, observe, and govern bidirectional handoffs without stitching together queues, summaries, routing rules, and analytics yourself.' },
  solutions: { eyebrow: 'SOLUTIONS', title: 'Continuity for every high-stakes customer journey.', text: 'HandoffOS adapts to regulated workflows, complex service operations, and AI-native products without forcing your team into a rigid helpdesk model.' },
  pricing: { eyebrow: 'PREDICTABLE PRICING', title: 'Start small. Scale without re-platforming.', text: 'Every plan includes bidirectional handoffs, context preservation, SDK access, and secure production infrastructure.' },
  developers: { eyebrow: 'DEVELOPER PLATFORM', title: 'One clean API between intelligence and expertise.', text: 'Typed SDKs, idempotent APIs, signed webhooks, an interactive playground, and observable delivery make production integration straightforward.' },
  documentation: { eyebrow: 'DOCUMENTATION', title: 'Go from project to production handoff in minutes.', text: 'Explore core concepts, quickstarts, SDK references, security guidance, and integration patterns for resilient conversation continuity.' },
  contact: { eyebrow: 'CONTACT', title: 'Design your handoff architecture with us.', text: 'Talk with a solutions architect about volume, security, compliance, migrations, or a custom enterprise deployment.' },
} as const

function PublicPage() {
  const { page } = Route.useParams()
  const data = pageData[page as keyof typeof pageData]
  return <MarketingLayout><main><section className="inner-hero page-width"><span className="eyebrow"><i /> {data.eyebrow}</span><h1>{data.title}</h1><p>{data.text}</p></section>{page === 'features' && <Features />}{page === 'solutions' && <Solutions />}{page === 'pricing' && <Pricing />}{page === 'developers' && <Developers />}{page === 'documentation' && <Documentation />}{page === 'contact' && <Contact />}</main></MarketingLayout>
}

function Features() {
  const cards = [[<Workflow />, 'Bidirectional orchestration', 'Route AI → human and human → AI transfers through the same consistent lifecycle.'], [<MessageSquareText />, 'Context preservation', 'Package transcripts, intent, entities, state, files, sentiment, and decisions into one portable envelope.'], [<Layers3 />, 'Handoff Context Preview', 'Inspect exactly what the receiving party gets before a transfer is delivered.'], [<Globe2 />, 'Real-time delivery', 'Track queued, active, completed, and failed handoffs with sub-second status changes.'], [<FileJson />, 'API keys and webhooks', 'Create scoped credentials, rotate secrets, and consume signed lifecycle events.'], [<ShieldCheck />, 'Governance and audit', 'Enforce workspace roles and retain an immutable record of configuration and access changes.'], [<PlugZap />, 'Integration fabric', 'Connect customer service, CRM, collaboration, data, and automation platforms.'], [<Boxes />, 'Projects and environments', 'Separate products, customers, regions, and test environments with independent credentials and metrics.']]
  return <section className="content-section page-width"><div className="large-card-grid">{cards.map(([icon, title, text]) => <article className="capability-card" key={String(title)}><span>{icon}</span><h2>{title}</h2><p>{text}</p><b>Included in every workspace →</b></article>)}</div></section>
}

function Solutions() {
  const solutions = [[<Headphones />, 'Customer support', 'Escalate from AI agents to specialists with every troubleshooting step, customer detail, and SLA timer intact.'], [<Landmark />, 'Financial services', 'Preserve verification state, risk signals, and disclosures as conversations move across automated and licensed teams.'], [<HeartHandshake />, 'Healthcare', 'Move intent and operational context safely while keeping protected data bounded to authorized workflows.'], [<Scale />, 'Legal and compliance', 'Capture decisions, source references, approvals, and policy constraints in an auditable transfer record.'], [<ShoppingBag />, 'Commerce', 'Carry cart, order, loyalty, and fulfillment context between shopping agents and human concierge teams.'], [<Code2 />, 'AI product teams', 'Add a production-grade human-in-the-loop layer without rebuilding orchestration, observability, and permissions.']]
  return <section className="content-section page-width"><div className="solution-list">{solutions.map(([icon, title, text], index) => <article key={String(title)}><b>0{index + 1}</b><span>{icon}</span><div><h2>{title}</h2><p>{text}</p></div><ArrowRight /></article>)}</div></section>
}

function Pricing() { return <section className="content-section page-width"><div className="pricing-grid pricing-grid--six">{pricingPlans.map((plan) => <article key={plan.id} className={plan.id === 'pro' ? 'pricing-card featured' : 'pricing-card'}>{plan.id === 'pro' && <span className="popular">MOST POPULAR</span>}<h2>{plan.name}</h2><p>{plan.note}</p><strong>{plan.price}<small>{plan.monthlyPriceCents ? '/month' : ''}</small></strong><b>{plan.handoffs} handoffs</b><ul><li><Check /> Bidirectional handoffs</li><li><Check /> Context preservation</li><li><Check /> SDK and API access</li>{plan.id === 'enterprise' && <li><Check /> Customisation included</li>}</ul><Link to={plan.id === 'enterprise' ? '/contact' : '/signup'} className={plan.id === 'pro' ? 'button button--primary' : 'button button--secondary'}>{plan.id === 'enterprise' ? 'Contact sales' : 'Choose plan'} <ArrowRight size={15} /></Link></article>)}</div><p className="pricing-note">All prices are monthly. Enterprise includes unlimited handoffs and customisation.</p></section> }

function Developers() { return <section className="content-section page-width"><div className="developer-page-grid"><div className="docs-nav"><span>QUICKSTART</span><b>1. Create a project</b><b>2. Generate a key</b><b>3. Install the SDK</b><b>4. Send a handoff</b><span>REFERENCE</span><b>Authentication</b><b>Handoffs API</b><b>Webhooks</b><b>Errors</b></div><div className="docs-body"><span className="kicker">QUICKSTART</span><h2>Send your first handoff</h2><p>Create a project in the dashboard, generate a secret key, and install the SDK for your runtime.</p><CodeBlock code={'npm install @handoffos/sdk'} /><h3>Initialize the client</h3><CodeBlock code={`import { HandoffOS } from '@handoffos/sdk'\n\nconst client = new HandoffOS({\n  apiKey: process.env.HANDOFFOS_API_KEY\n})`} /><h3>Create a context-rich handoff</h3><CodeBlock code={`await client.handoffs.create({\n  direction: 'ai_to_human',\n  conversation_id: 'conv_98AB',\n  context: { summary, messages, customer },\n  reason: 'Specialist review required'\n})`} /><Link to="/signup" className="button button--primary">Open API Playground <TerminalSquare size={16} /></Link></div></div></section> }

function Documentation() { const groups = [['Getting started', 'Platform overview', 'Core concepts', 'Quickstart', 'Environments'], ['Build', 'Handoffs API', 'Context envelopes', 'Webhooks', 'Idempotency'], ['Operate', 'Analytics', 'Usage and limits', 'Audit logs', 'Incident handling'], ['Secure', 'Authentication', 'Key rotation', 'Roles and permissions', 'Data retention']]; return <section className="content-section page-width"><div className="documentation-grid">{groups.map(([title, ...items]) => <article key={title}><BookOpen /><h2>{title}</h2>{items.map((item) => <Link key={item} to="/developers">{item}<ArrowRight /></Link>)}</article>)}</div><div className="docs-callout"><LifeBuoy /><div><h2>Need implementation guidance?</h2><p>Open a support ticket from your dashboard or work with a HandoffOS solutions architect.</p></div><Link to="/contact" className="button button--secondary">Contact support</Link></div></section> }

function Contact() {
  const [state, setState] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState('sending'); const data = new FormData(event.currentTarget); try { const response = await fetch('/__forms.html', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(data as unknown as Record<string, string>).toString() }); if (!response.ok) throw new Error(); setState('sent'); event.currentTarget.reset() } catch { setState('error') } }
  return <section className="content-section page-width contact-grid"><div><h2>Tell us what you're building.</h2><p>We typically respond within one business day.</p><div className="contact-point"><ShieldCheck /><span><b>Security review</b>SOC 2 planning, data residency, retention, and architecture.</span></div><div className="contact-point"><Code2 /><span><b>Technical design</b>Volume modeling, integrations, migration, and reliability.</span></div><div className="contact-point"><MessageSquareText /><span><b>Commercial questions</b>Custom usage, procurement, enterprise support, and SLAs.</span></div></div><form name="enterprise-contact" method="POST" data-netlify="true" onSubmit={submit} className="contact-form"><input type="hidden" name="form-name" value="enterprise-contact" /><label className="honeypot">Do not fill<input name="bot-field" /></label><div className="form-row"><label>First name<input name="first-name" required /></label><label>Last name<input name="last-name" required /></label></div><label>Work email<input name="email" type="email" required /></label><label>Company<input name="company" required /></label><label>What do you need to hand off?<textarea name="message" rows={5} required /></label><button className="button button--primary button--large" disabled={state === 'sending'}>{state === 'sending' ? 'Sending…' : 'Talk to an architect'} <ArrowRight size={16} /></button>{state === 'sent' && <p className="form-success">Thanks—your message is safely queued for our team.</p>}{state === 'error' && <p className="form-error">We could not send that message. Please try again.</p>}</form></section>
}

function CodeBlock({ code }: { code: string }) { return <pre className="docs-code"><button onClick={() => void navigator.clipboard.writeText(code)}>Copy</button><code>{code}</code></pre> }
