import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { AuthError, updateUser } from '@netlify/identity'
import { ArrowRight, LoaderCircle, LockKeyhole } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Logo } from '@/components/logo'
import { useAuth } from '@/lib/auth'

export const Route = createFileRoute('/reset-password')({ component: ResetPassword })
function ResetPassword() { const { user, loading, callbackType } = useAuth(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get('password')); const confirm = String(data.get('confirm')); if (password !== confirm) { setError('Passwords do not match.'); return } setBusy(true); try { await updateUser({ password }); window.sessionStorage.removeItem('handoffos-recovery'); await navigate({ to: '/dashboard' }) } catch (failure) { setError(failure instanceof AuthError ? failure.message : 'Unable to update your password.') } finally { setBusy(false) } } return <main className="single-auth"><Logo /><div className="single-auth-card"><span className="auth-overline">SECURE PASSWORD RESET</span><h1>Choose a new password</h1><p>Use at least 8 characters. Your new password takes effect immediately.</p>{loading ? <LoaderCircle className="spin" /> : !user || callbackType !== 'recovery' ? <div className="auth-error">This recovery session is missing or expired. <Link to="/forgot-password">Request a new link.</Link></div> : <form onSubmit={submit}><label>New password<div className="input-icon"><LockKeyhole /><input name="password" type="password" minLength={8} required /></div></label><label>Confirm password<div className="input-icon"><LockKeyhole /><input name="confirm" type="password" minLength={8} required /></div></label>{error && <div className="auth-error">{error}</div>}<button className="button button--primary auth-submit" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <>Update password <ArrowRight /></>}</button></form>}</div></main> }
